server:
  port: 8000

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info

spring:
  cloud:
    gateway:
      routes:
        - uri: lb://WORKER-MS
          predicates:
            - Path=/worker/**
          filters:
            - StripPrefix=1
  application:
    name: gateway-api
